@startuml LibraryClasses

    package platform {
      class RpmcLib {
        +RequestMonotonicCounter (Index, *Value)
        +IncrementMonotonicCounter (Index)
      }

      class KeyServicePpi {
        +GenerateKey (*Salt,SaltSize,*Key,KeySize,PreviousKey)
      }
    }

    package edk2 {
      class ProtectedVariableLib {
        +ProtectedVariableLibInitialize (*ContextIn)
        +ProtectedVariableLibFindNext (*NameSize,*Name,*Guid)
        +ProtectedVariableLibFindNextEx (*VarInfo)
        +ProtectedVariableLibGetByName (*Name,*Guid,*Attr,*Size,*Data)
        +ProtectedVariableLibGetByBuffer (*Var,*Size,*Data,Auth)
        +ProtectedVariableLibGetByInfo (*VarInfo)
        +ProtectedVariableLibWriteInit ()
        +ProtectedVariableLibUpdate ()
        +ProtectedVariableLibWriteFinal ()
        +ProtectedVariableLibReclaim ()
      }

      class EncryptionVariableLib {
        +EncryptVariable (*VarInfo)
        +DecryptVariable (*VarInfo)
        +GetCipherDataInfo (*VarInfo)
        +SetCipherDataInfo (*VarInfo)
      }

      class VariableKeyLib {
        +GetVariableKey (*Key, *Size)
        +RegenerateVariableKey ()
        +LockVariableKeyInterface ()
      }
    }

    ProtectedVariableLib --> EncryptionVariableLib
    ProtectedVariableLib --> RpmcLib
    ProtectedVariableLib --> VariableKeyLib
    VariableKeyLib --> KeyServicePpi

@enduml