@startuml ProtectedVariableLib instances
    ProtectedVariableLib <|-- PeiProtectedVariableLib
    PeiProtectedVariableLib : ProtectedVariableLibInitialize()
    PeiProtectedVariableLib : ProtectedVariableLibGetByName()
    PeiProtectedVariableLib : ProtectedVariableLibGetByBuffer()
    PeiProtectedVariableLib : ProtectedVariableLibGetByInfo()
    PeiProtectedVariableLib : ProtectedVariableLibFindNext()
    PeiProtectedVariableLib : ProtectedVariableLibFindNextEx()

    ProtectedVariableLib <|-- SmmProtectedVariableLib
    SmmProtectedVariableLib : ProtectedVariableLibInitialize()
    SmmProtectedVariableLib : ProtectedVariableLibFindNext()
    SmmProtectedVariableLib : ProtectedVariableLibFindNextEx()
    SmmProtectedVariableLib : ProtectedVariableLibGetByName()
    SmmProtectedVariableLib : ProtectedVariableLibGetByBuffer()
    SmmProtectedVariableLib : ProtectedVariableLibGetByInfo()
    SmmProtectedVariableLib : ProtectedVariableLibWriteInit()
    SmmProtectedVariableLib : ProtectedVariableLibWriteFinal()
    SmmProtectedVariableLib : ProtectedVariableLibUpdate()
    SmmProtectedVariableLib : ProtectedVariableLibReclaim()

    ProtectedVariableLib <|-- SmmRuntimeProtectedVariableLib
    SmmRuntimeProtectedVariableLib : ProtectedVariableLibInitialize()
    SmmRuntimeProtectedVariableLib : ProtectedVariableLibGetByName()

    ProtectedVariableLib <|-- DxeRuntimeProtectedVariableLib
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibInitialize()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibFindNext()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibFindNextEx()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibGetByName()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibGetByBuffer()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibGetByInfo()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibWriteInit()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibUpdate()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibWriteFinal()
    DxeRuntimeProtectedVariableLib : ProtectedVariableLibReclaim()

    VariablePei ..> PeiProtectedVariableLib
    VariableSmm ..> SmmProtectedVariableLib
    VariableSmmRuntime ..> SmmRuntimeProtectedVariableLib
    VariableRuntimeDxe ..> DxeRuntimeProtectedVariableLib
@enduml
